### ISSUE TITLE
Epica 001 - Conformación del equipo y Generación del respositorio

### ISSUE THREAD

**Issue by GitJN-1** [Runteams-MisionTIC/Proyecto_web#3]
Dado la conformacion de un equipo de trabajo y una herramienta para administrar las fuentes/artefactos en la nube

Cuando sea necesario generar un grupo, asignar roles y crear un repositorio con mi propia cuenta

Entonces dispondré de un lugar en Trello y GitHub para llevarseguimiento a las historias y para almacenar la información/artefactos/fuentes de los proyectos de desarrollo.

- [x] Crear un grupo de trabajo.

- [x] Vincular a los integrantes del grupo de trabajo.

- [x] Asignación de roles.

- [x] Generar el repositorio

- [x] Vincular git con GitHub

**Comment by GitJN-1** [comment]
Se genera y actualiza una ¨epica¨ para las historias de usuario del Sprint 1
